- name: Azure VM Deallocate
  hosts: localhost
  connection: local
  tasks:
  - name: Deallocate
    azure_rm_virtualmachine:
     resource_group: myResourceGroupAnsible
     name: myVM
     allocated: no
