- name: Azure remove resourcegroup
  hosts: localhost
  connection: local
  tasks:
  - name: delete a resource group
    azure_rm_resourcegroup:
     name: myResourceGroupAnsible
     state: absent
     force: yes
